"""
LocalActions example — node-local (off-chain) streams via the admin port,
with optional operator-key authentication.

Local streams live entirely on a single node:
  - no consensus broadcast, no transaction fees
  - implicitly owned by the node operator (data_provider is server-derived
    from the node's secp256k1 key — clients never supply it)
  - reachable through kwild's admin JSON-RPC server, NOT the gateway

When the node has [extensions.tn_local] require_signature = "true", every
admin call must carry a signature recoverable to the node operator's
address. Pass the operator key via --operator-key (or set OPERATOR_KEY).
Without the flag, the SDK works against an unsigned node too — auth is
opt-in, additive on top of kwild's transport auth.

Flow:
  1. Connect to the admin server (with or without an operator-key signer)
  2. (If a key is set) Demonstrate that a wrong key is rejected
  3. Create a primitive stream, insert 5 records, read them back, query the index
  4. Create a 2-child composed stream + taxonomy, query the weighted result,
     then disable the taxonomy to confirm soft-delete
  5. Confirm the streams appear in list_streams (data_provider is the node's
     own address, lowercased)
  6. Clean up everything

Run against a local node spun up with `task single:start:admin` from the
node repo (admin RPC on http://127.0.0.1:8485). To exercise the auth path,
start the node with TN_LOCAL_REQUIRE_SIGNATURE=true and pass the operator key:

  # 1. Start the node with auth required
  TN_LOCAL_REQUIRE_SIGNATURE=true task single:start:admin

  # 2. Pull the autogenerated operator key out of the container
  OPERATOR_KEY=$(docker exec tn-db cat /root/.kwild/nodekey.json | jq -r '.key')

  # 3. Run the example
  python examples/local_actions_example/main.py --operator-key=$OPERATOR_KEY
"""

import argparse
import os
import secrets
import sys
from datetime import datetime, timezone
from typing import Optional

from trufnetwork_sdk_py import (
    LocalClient,
    STREAM_TYPE_COMPOSED,
    STREAM_TYPE_PRIMITIVE,
)
from trufnetwork_sdk_py.utils import generate_stream_id

ADMIN_URL = "http://127.0.0.1:8485"


def _date_to_unix(date: datetime) -> int:
    return int(date.replace(tzinfo=timezone.utc).timestamp())


def _safe_delete(local: LocalClient, stream_id: str) -> None:
    """Best-effort delete — never raises."""
    try:
        local.delete_stream(stream_id)
    except Exception:
        pass


def _load_operator_key() -> Optional[str]:
    """Resolve the operator key from --operator-key or $OPERATOR_KEY.
    Returns None when neither is set — the example then runs unsigned."""
    parser = argparse.ArgumentParser(
        description="tn_local admin example with optional operator-key auth",
    )
    parser.add_argument(
        "--operator-key",
        default=os.environ.get("OPERATOR_KEY", ""),
        help=(
            "Operator's secp256k1 private key (hex, 0x prefix optional). "
            "Required when the node has require_signature=true. Pull it "
            "from `docker exec tn-db cat /root/.kwild/nodekey.json | "
            "jq -r '.key'` for the dev node."
        ),
    )
    args = parser.parse_args()
    return args.operator_key or None


def _demonstrate_wrong_key_rejection() -> None:
    """Sign requests with a *different* key from the node operator's,
    expecting the server to reject them. This is the payoff of the auth
    feature — proof that admin port reachability alone no longer lets a
    caller act as the operator."""
    wrong_key = secrets.token_hex(32)
    print("\n[wrong-key check] signing with a freshly generated key (NOT the operator)")
    wrong_local = LocalClient(ADMIN_URL, private_key=wrong_key)
    try:
        wrong_local.create_stream(
            generate_stream_id("wrong-key-attempt"),
            STREAM_TYPE_PRIMITIVE,
        )
    except Exception as rejected:
        print(f"  rejected (expected): {rejected}")
        return
    print("  unexpected: server ACCEPTED a wrong-key signed request — auth is broken")
    sys.exit(1)


def main() -> None:
    operator_key = _load_operator_key()

    if operator_key is None:
        print("no --operator-key set — running unsigned (works only on "
              "require_signature=false nodes)")
        local = LocalClient(ADMIN_URL)
    else:
        print("signing requests with the supplied operator key")
        local = LocalClient(ADMIN_URL, private_key=operator_key)
    print(f"connected to admin server at {ADMIN_URL}")

    # If the operator key is configured, prove that a different key is
    # rejected before doing real work — both for confidence and as a
    # runnable example of the property that closes the threat model.
    if operator_key is not None:
        _demonstrate_wrong_key_rejection()

    primitive_id = generate_stream_id("local-actions-example-primitive")
    child_a_id = generate_stream_id("local-actions-example-child-a")
    child_b_id = generate_stream_id("local-actions-example-child-b")
    composed_id = generate_stream_id("local-actions-example-composed")

    # Drop anything left from a previous run.
    for sid in (primitive_id, child_a_id, child_b_id, composed_id):
        _safe_delete(local, sid)

    try:
        # ─── Primitive stream ──────────────────────────────────────
        print(f"\nprimitive stream: {primitive_id}")
        local.create_stream(primitive_id, STREAM_TYPE_PRIMITIVE)

        start = datetime(2024, 1, 1)
        records = [
            {"event_time": _date_to_unix(start.replace(day=i + 1)), "value": float(i + 1)}
            for i in range(5)
        ]
        local.insert_records(primitive_id, records)
        print(f"  inserted {len(records)} records")

        retrieved = local.get_record(
            primitive_id,
            from_time=records[0]["event_time"],
            to_time=records[-1]["event_time"],
        )
        print(f"  read back: {len(retrieved)} records")
        for r in retrieved[:3]:
            print(f"    event_time={r['event_time']} value={r['value']}")

        index = local.get_index(
            primitive_id,
            from_time=records[0]["event_time"],
            to_time=records[-1]["event_time"],
        )
        # baseTime defaults to earliest event_time → first index value is 100.
        print(f"  index[0]={index[0]['value']}, index[-1]={index[-1]['value']}")

        # ─── Composed stream + taxonomy ────────────────────────────
        print(f"\ncomposed stream: {composed_id} (children: {child_a_id}, {child_b_id})")
        local.create_stream(child_a_id, STREAM_TYPE_PRIMITIVE)
        local.create_stream(child_b_id, STREAM_TYPE_PRIMITIVE)
        local.create_stream(composed_id, STREAM_TYPE_COMPOSED)

        t = _date_to_unix(datetime(2024, 6, 1))
        local.batch_insert_records(
            [
                {"stream_id": child_a_id, "inputs": [{"event_time": t, "value": 100}]},
                {"stream_id": child_b_id, "inputs": [{"event_time": t, "value": 200}]},
            ]
        )

        local.insert_taxonomy(
            stream_id=composed_id,
            child_stream_ids=[child_a_id, child_b_id],
            weights=["1", "1"],
            start_date=t,
        )

        composed_records = local.get_record(composed_id, from_time=t, to_time=t)
        # Equal weights on 100 and 200 → weighted average 150.
        print(f"  composed value at {t}: {composed_records[0]['value']} (expect ~150)")

        # group_sequence=1 because this is the only taxonomy ever inserted on this parent.
        local.disable_taxonomy(composed_id, group_sequence=1)
        after_disable = local.get_record(composed_id, from_time=t, to_time=t)
        print(f"  after disable_taxonomy: {len(after_disable)} records (expect 0)")

        # ─── List streams ──────────────────────────────────────────
        owned_ids = {primitive_id, child_a_id, child_b_id, composed_id}
        listed = local.list_streams()
        ours = [s for s in listed if s["stream_id"] in owned_ids]
        print(f"\nlist_streams: {len(ours)}/{len(owned_ids)} created streams visible")
        if ours:
            print(f"  data_provider: {ours[0]['data_provider']} (server-derived)")
    finally:
        for sid in (primitive_id, child_a_id, child_b_id, composed_id):
            _safe_delete(local, sid)
        print("\ncleanup done.")


if __name__ == "__main__":
    main()
